AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Consumer lambda with

Resources:
  FormConsumerDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: form-consumer-DLQ
      MessageRetentionPeriod: 1209600 # Setup to the maximum (14 days)

  FormConsumerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: form-consumer-queue
      ReceiveMessageWaitTimeSeconds: 20
      MessageRetentionPeriod: 345600 # Setup to explicity default value (4 days)
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FormConsumerDLQ.Arn
        maxReceiveCount: 3

  FormsTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FormsTable
      AttributeDefinitions:
        - AttributeName: 'FormId'
          AttributeType: 'S'
        - AttributeName: 'CreatedDate'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'FormId'
          KeyType: 'HASH'
        - AttributeName: 'CreatedDate'
          KeyType: 'RANGE'
      BillingMode: 'PAY_PER_REQUEST'
      
  FormConsumerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: '/'
      Policies:
      - PolicyName: Logs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: 
            - logs:*
            Resource: arn:aws:logs:*:*:*
      - PolicyName: 'DynamoDBFullaccess'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: 
            - dynamodb:*
            Resource: !GetAtt FormsTable.Arn
      - PolicyName: 'SQSFullaccess'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: 
            - sqs:GetQueueUrl
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:ChangeMessageVisibility
            - sqs:GetQueueAttributes
            - sqs:ListQueues
            Resource: !GetAtt FormConsumerQueue.Arn
      ManagedPolicyArns:
              - 'arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy'

  FormConsumerLambda:
    Type: AWS::Serverless::Function 
    Properties:
      Tracing: Active
      Layers:
        - !Ref Libs
        - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
      CodeUri: .
      Handler: app.handler
      Runtime: nodejs12.x
      Timeout: 30
      Role: !GetAtt FormConsumerLambdaRole.Arn
      MemorySize: 256
      Events:
        FormConsumerMessage:
          Type: SQS
          Properties:
            Queue: !GetAtt FormConsumerQueue.Arn
            BatchSize: 10

  Libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: consumer-nodejs-lib
      Description: Dependencies for the consumer lambda.
      ContentUri: ../lib/.
      CompatibleRuntimes:
        - nodejs10.x
        - nodejs12.x
        - nodejs14.x

Outputs:
  FormConsumerLambda:
    Description: FormConsumerLambda function name
    Value: !Ref FormConsumerLambda
  
  FormConsumerQueueName:
    Description: SQS queue name
    Value: !GetAtt FormConsumerQueue.QueueName

  FormConsumerQueueArn:
    Description: SQS queue ARN
    Value: !GetAtt FormConsumerQueue.Arn

  FormConsumerQueueUrl:
    Description: SQS queue URL
    Value: !Ref FormConsumerQueue